client_config_backend: settings
client_config:
client_id: 818688018921-63rtuh5tju48mf74m0lqrv6nqpm04b0e.apps.googleusercontent.com
client_secret: your_client_secretsave_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
- https://www.googleapis.com/auth/drive.fil